name: Day 01 - Workflow Fundamentals
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'
   
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Show workflow name
        run: |
          echo "Workflow: ${{ github.workflow }}"
      - name: Show runner information
        run: |
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
      - name: Run Unit tests
        run: npm test
      - name: Build application
        run: npm run build
